### ISSUE TITLE
Version of After Effects is hardcoded

### ISSUE THREAD

**Issue by diroru** [seblavoie/After-Effects-Scripting-Sublime-Text-Package#6]
Hi! First of all, thanks for the great extension!

On OS X (10.10.4), you need to manually set the version in _build.sh_ and _run.scpt_ (two occurences in the latter.) It is not a huge hassle, still it would be nice, if it was at least documented.

Also, it works on the latest Sublime Text (v. 3), i think this should be noted as well.

Cheers,
dimitar

**Comment by seblavoie** [comment]
You mean the After Effects version? If yes I know, but haven't found the time to implement an easy way to make it work with the latest version. Since I don't really use this package anymore I am not sure I will make time for it any time soon, but I'd sure merge pull requests improving it. I added a note in the readme though.

About v. 3, I cannot get it to work. Care to explain what you did to make it work?

**Comment by diroru** [comment]
Well, actually, just followed the instructions and cloned the project into: <pre>~/Library/Application\ Support/Sublime\ Text\ 3/Packages/AfterEffects</pre> Then i merely had to correct the AE version.

– What are your symptoms? (or should this be handled in another issue? :)
– Would you like me to update the readme and send you a pull request?

**Comment by seblavoie** [comment]
Great! Uninstalling and reinstalling fixed the issue. I removed replaces references to Sublime Text 2 with just Sublime Text and changed default versions to CC 2015. Thanks!
